// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'flutter_application_1';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String AVENIR_BOOK = 'Avenir-Book';
  static const String AVENIR_HEAVY = 'Avenir-Heavy';
  static const String AVENIR_LIGHT = 'Avenir-Light';
  static const String AVENIR_MEDIUM = 'Avenir-Medium';
}
